version: '3.7'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=Operations_plan
      - DOCKER_INFLUXDB_INIT_PASSWORD=Operations_plan
      - DOCKER_INFLUXDB_INIT_ORG=MAN
      - DOCKER_INFLUXDB_INIT_BUCKET=OPCUA
      - INFLUXD_HTTP_FLUX_ENABLED=false  # Disable Flux to force InfluxQL usage

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    user: root
    restart: always
    entrypoint: /bin/bash -c "chmod 777 /var/run/docker.sock && /entrypoint.sh telegraf"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/hostfs:ro
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - '3100:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data: